global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/recording-rules.yml
  - /etc/prometheus/rules/alert-rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: rebootfocus-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:10080

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - rebootfocus-postgres-exporter:9187
